//! lava-azurerm — autogenerated typed resource catalog for the
//! azurerm terraform provider. Mirrors pangea-azurerm.

#![allow(clippy::module_name_repetitions)]

pub const RESOURCES_DIR: &str = "resources";

pub const RESOURCES: &[&str] = &[
    "azurerm_key_vault",
    "azurerm_kubernetes_cluster",
    "azurerm_resource_group",
    "azurerm_storage_account",
    "azurerm_subnet",
    "azurerm_virtual_network",];

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn every_registered_resource_has_a_tlisp_file() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        for name in RESOURCES {
            let p = base.join(format!("{name}.tlisp"));
            assert!(p.exists(), "missing typed shape on disk: {}", p.display());
        }
    }
    #[test]
    fn index_tlisp_exists() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(RESOURCES_DIR);
        assert!(base.join("_index.tlisp").exists());
    }
    #[test]
    fn schema_json_present() {
        let base = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        assert!(base.join("schema.json").exists());
    }
    #[test]
    fn at_least_one_resource_registered() {
        assert!(!RESOURCES.is_empty());
    }
}
